resources:
  Dbp\Relay\FrontendBundle\Entity\User:
    types: ['http://schema.org/Thing']
    shortName: "FrontendUser"
    description: "A frontend user"
    normalizationContext:
      groups: ["FrontendUser:output"]
      jsonld_embed_context: true
    operations:
      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\FrontendBundle\State\UserProvider
        uriTemplate: "/frontend/users"
        openapiContext:
          tags: ["Frontend"]
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\FrontendBundle\State\UserProvider
        uriTemplate: "/frontend/users/{identifier}"
        openapiContext:
          tags: ["Frontend"]
    properties:
      identifier:
        identifier: true
