services:
  Dbp\Relay\FrontendBundle\State\:
    resource: '../../State'
    autowire: true
    autoconfigure: true

  Dbp\Relay\FrontendBundle\Service\FrontendUserProvider:
    autowire: true
    autoconfigure: true
