services:
  Dbp\Relay\FrontendBundle\Rest\UserProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\FrontendBundle\Service\FrontendUserProvider:
    autowire: true
    autoconfigure: true
