services:
  Dbp\Relay\FrontendBundle\DataPersister\:
    resource: '../../DataPersister'
    autowire: true
    autoconfigure: true

  Dbp\Relay\FrontendBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  Dbp\Relay\FrontendBundle\Service\FrontendUserProvider:
    autowire: true
    autoconfigure: true
